export const BodyStyles = {
    mainContainer: {
        display: 'flex',
        flexDirection: 'column' as const,
        width: '100%',
        top: "10px",
        position: "relative" as const,
        backgroundColor: 'var(--bg-color)',
        backgroundImage: 'var(--bg-img)',
        backgroundPosition: 'center',
    },
    graphContainer: {
        width: '100vw',
        height: '90vh',
        marginTop: '3rem',
        justifyContent: 'center' as const,
        display: 'flex',
        alignItems: 'center',
        position: 'relative' as const,
        flexWrap: 'wrap' as const,
    },
    chartButtonColumn: {
        position: "absolute" as const,
        display: "flex",
        flexDirection: "column" as const,
        left: "10px",
        gap: "5px",
        top: '50%',
        transform: 'translateY(-50%)',
        zIndex: "1000",
    },
    chartButton: {
/*        padding: '8px',*/
        border: 'none',
        borderRadius: '8px',
/*        fontSize: '1rem',*/
        textAlign: 'center' as const,
        transition: 'background-color 0.3s ease, color 0.3s ease, transform 0.2s ease',
        boxShadow: '0px 4px 6px rgba(0, 0, 0, 0.1)',
        zIndex: '1000',
    },
    newFileButton: {
        position: "absolute" as const,
        top: "10px",
        width: "15vw",
        left: "50%",
        transform: "translateX(-50%)",
        alignItems: "center",
        justifyContent: "center",
        padding: "10px 20px",
        fontSize: "1rem",
        border: "none",
        borderRadius: "5px",
        cursor: "pointer",
        transition: "background-color 0.3s ease, color 0.3s ease",
        zIndex: "1000",
    },
};
