export const WelcomePageStyles = {
    container: {
        display: 'flex',
        flexDirection: 'column' as const,
        justifyContent: 'flex-start',
        alignItems: 'center',
        height: '100vh',
        padding: '0 20px',
        paddingTop: '10vh',
        backgroundColor: 'var(--background-color)',
        backgroundImage: 'var(--background-image)',
        backgroundPosition: 'center',
    },
    title: {
        fontSize: '3rem',
        marginBottom: '1rem',
        color: 'var(--text-color)',
    },
    description: {
        fontSize: '1.2rem',
        textAlign: 'center' as const,
        marginBottom: '2rem',
        color: 'var(--text-color)',
        maxWidth: '600px',
    },
    getStartedButton: {
        padding: '10px 20px',
        fontSize: '1.2rem',
        color: 'var(--button-text-color)',
        backgroundColor: 'var(--button-background)',
        border: 'none',
        borderRadius: '5px',
        cursor: 'pointer',
        transition: 'background-color 0.3s ease, color 0.3s ease',
    },
    darkModeButton: {
        position: 'absolute' as const,
        top: '20px',
        right: '20px',
        padding: '10px 20px',
        fontSize: '1rem',
        color: 'var(--button-text-color)',
        backgroundColor: 'var(--button-background)',
        border: 'none',
        borderRadius: '5px',
        cursor: 'pointer',
        transition: 'background-color 0.3s ease, color 0.3s ease',
    },
};
